[WIP] add docker-compose in backend/ to orchestrate backend
codeforsanjose/gov-agenda-notifier pull request #100
Opened 2021-01-13 05:19 UTC by sent-hil

### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
Adds the ability to bring up the two required services for backend with a single command: `docker-compose up --build --remove-orphans`.

- Describe what changes are being made
Add `docker-compose.yml` file to `backend/` folder.

- Describe why these changes are being made

- List the use cases and edge cases relevant to this PR

- Describe how errors will be handled. How will we know if this code breaks in production

- Describe any external libraries/dependencies added or removed in this PR

- Describe any security risks are there regarding this change

- Describe how you tested these changes
1. Ran `docker-compose up --build --remove-orphans` from backend/ folder
2. Went to `localhost:8080` in browser and ran `{ getAllMeetings { id } }` in the input box.
3. Made changes to `backend/graphql_api/lambda/handler.js` and saw the container was restarted.

- Link to relevant external documentation

--------------------------
### :clipboard: Mandatory Checklist

- [x] Example of a checked item (please remove when creating your Pull Request) 

- [ ] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [ ] Have you discussed these changes with the project leader(s)?
- [ ] Do all variable and function names communicate what they do?
- [ ] Were all the changes commented and / or documented?
- [ ] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [ ] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [ ] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
### :framed_picture: Screenshots and Screen Recordings

#### Before

#### After
<img width="1440" alt="Screen Shot 2021-01-12 at 9 11 30 PM" src="https://user-images.githubusercontent.com/164864/104409309-d706f480-551a-11eb-8b30-600da6c733c5.png">

--------------------------
### :blue_book: Glossary
- PR = Pull Request

2021-01-13 06:46 UTC, sent-hil commented
@teohrt please take a look at the PR and let me know your thoughts. It's not a hard requirement for everyone to switch to using docker-compose for development, but it might be useful for those having issues bringing up backend services. From what I can tell existing developer workflow is not affected but I'm not a react developer.

2021-01-18 05:31 UTC, teohrt commented
> @teohrt please take a look at the PR and let me know your thoughts. It's not a hard requirement for everyone to switch to using docker-compose for development, but it might be useful for those having issues bringing up backend services. From what I can tell existing developer workflow is not affected but I'm not a react developer.

Beautiful! docker-compose will really make onboarding easier. Could you add some documentation in the README for that new workflow?

2021-01-18 05:32 UTC, teohrt requested changes
Great stuff! Can you add documentation to the README for the new workflow?

2021-01-21 03:50 UTC, sent-hil commented
> Great stuff! Can you add documentation to the README for the new workflow?

Done!

2021-01-21 17:06 UTC, JMStudiosJoe submitted a review, later dismissed
lgtm is ready for merge?

2021-01-21 17:07 UTC, JMStudiosJoe commented
I think since @teohrt requested the changes he needs to be the approver :)

2021-01-22 03:36 UTC, anna-kartynnik commented on frontend/package-lock.json
> -      },
Do we need to change this file? It seems this PR shouldn't touch frontend 🤔...

2021-01-22 03:47 UTC, JMStudiosJoe commented on frontend/package-lock.json
> -      },
agreed @sent-hil do you need this change or can you remove from this pr?

2021-01-22 04:12 UTC, JMStudiosJoe commented on docker-compose.yml
> +  postgres-data:
add space plz

2021-01-22 04:27 UTC, JMStudiosJoe approved these changes
LGTM

2021-01-22 04:27 UTC, merged

2021-01-22 04:29 UTC, sent-hil commented on frontend/package-lock.json
> -      },
thank you @anna-kartynnik