[Wip] Send email in same flow as text message when meeting starts
codeforsanjose/gov-agenda-notifier pull request #102
Opened 2021-01-15 04:57 UTC by sent-hil

# TODOS:
- [ ] Remove exploratory TODOs.
- [ ] Update Readme to include how to setup AWS SES.
- [ ] Update email body with starter template.

### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
Send email in the same flow as SMS when the meeting starts. Closes https://github.com/codeforsanjose/gov-agenda-notifier/issues/97

- Describe what changes are being made
Creates sesClient which sends email through AWS SES.

- Describe how errors will be handled. How will we know if this code breaks in production
Errors due to AWS SES API are logged using `logger`.

- Describe any external libraries/dependencies added or removed in this PR
aws-sdk added.

- Describe any security risks are there regarding this change
None.

- Describe how you tested these changes
Made this change on graphql API frontend and saw email was sent.
```
mutation {
  updateMeeting(
    id: 1,
    status: "IN PROGRESS",
    meeting_start_timestamp: "10",
    meeting_end_timestamp: "10",
    virtual_meeting_url:"https://google.com",
    meeting_type:"test"
  ) {
  	status
  }
}
```

- Link to relevant external documentation

--------------------------
### :clipboard: Mandatory Checklist
- [ ] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [ ] Have you discussed these changes with the project leader(s)?
- [ ] Do all variable and function names communicate what they do?
- [ ] Were all the changes commented and / or documented?
- [ ] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [ ] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [ ] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
### :framed_picture: Screenshots and Screen Recordings

#### Before

#### After

--------------------------
### :blue_book: Glossary
- PR = Pull Request

2021-01-18 05:26 UTC, teohrt requested changes
Awesome! Just a few things to shore up but this is great.

In addition to my other comments, I love that docker-compose flow. Can you update the README with some documentation on it before it hits master?

2021-01-18 05:26 UTC, teohrt commented on backend/graphql_api/lambda/controllers/subscriptionsController.js
> +// TODOS: who calls this?
My apologies for that export pattern. I wasn't yet familiar with any javascript dependency injection frameworks so this was my manual solution. 

Searching the codebase for the filename is a decent strategy in this situation though. The `requires` will pop up.

It's used in the mutation resolvers here: 
https://github.com/codeforsanjose/gov-agenda-notifier/blob/6c7baa866506089ce58d078b34023771da5f3b4d/backend/graphql_api/lambda/graphql/resolvers/mutation.js#L4

Don't forget to remove this question if you're happy with the answer

2021-01-21 03:56 UTC, sent-hil commented
@teohrt my bad for leaving those random todos, i was just trying to understand the codebase and accidentally pushed them 😬

2021-01-22 05:00 UTC, sent-hil commented on backend/graphql_api/lambda/controllers/subscriptionsController.js
> +  // TODOS: this notifies users meeting itself is starting
removed it

2021-01-22 05:05 UTC, JMStudiosJoe approved these changes
looks great

2021-01-22 05:06 UTC, merged