Parameterize query strings without interpolation
codeforsanjose/gov-agenda-notifier pull request #162
Opened 2021-03-21 23:57 UTC by forkitupforkitup

Closes #142 
### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
[Parameterizes the strings we use to query the PostgreSQL database to help prevent SQL injection.](https://node-postgres.com/features/queries#Parameterized%20query)

- Describe what changes are being made
`backend/graphql_api/lambda/db/dbClient.js`
`backend/agenda_upload_service/lambda/db/dbClient.js`
In these two files, any SQL query strings composed with ECMAScript 6 string interpolation were modified. Also, the `query` constant in each file was changed to accept extra arguments.

- Describe why these changes are being made
Using ES6 interpolation to feed a SQL query string makes it easy for an end user to compose SQL. End users should not be composing SQL.

- List the use cases and edge cases relevant to this PR
This addresses the edge case in which an informed user would like to compose SQL queries, particularly in any text fields available in the front end. It's not clear to me how many opportunities really exist at this point, but this aims to establish a precedent for future development.

- Describe how errors will be handled. How will we know if this code breaks in production
We will know I messed up when GraphQL queries and mutations return unexpected results.

- Describe any external libraries/dependencies added or removed in this PR
none

- Describe any security risks are there regarding this change
No security risks.

- Describe how you tested these changes
Going to test these in the GraphQL playground right now.

- Link to relevant external documentation
https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-injection?view=sql-server-ver15

--------------------------
### :clipboard: Mandatory Checklist

- [x] Example of a checked item (please remove when creating your Pull Request) 

- [x] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [x] Have you discussed these changes with the project leader(s)?
- [x] Do all variable and function names communicate what they do?
- [x] Were all the changes commented and / or documented?
- [x] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [x] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [ ] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
### :framed_picture: Screenshots and Screen Recordings

#### Before

#### After

--------------------------
### :blue_book: Glossary
- PR = Pull Request

2021-03-23 00:12 UTC, sent-hil requested changes

2021-03-23 00:12 UTC, sent-hil commented on backend/graphql_api/lambda/db/dbClient.js
> +    const queryString = 'SELECT * FROM meeting WHERE id = $1'
is there a reason you created a separate variable for this instead of just inlining it in `query()`?

2021-03-23 00:12 UTC, sent-hil commented on backend/agenda_upload_service/lambda/db/dbClient.js
> +  const query = async (queryString, ...args) => {
since you are always calling query with args as an array, is `...` required?

alternatively, you can not pass in an array, which would make sense of single params like https://github.com/codeforsanjose/gov-agenda-notifier/pull/162/files#diff-ba995098cb45be0aaebbe3522ab8e18f4c7087eb38f2935a9e64611e6b2c6ca2R125

2021-03-23 00:12 UTC, sent-hil commented
also i would not commit frontend/package-lock.json as part of this PR...something is screwed up with that file and needs further debugging

2021-03-23 00:24 UTC, forkitupforkitup commented on backend/agenda_upload_service/lambda/db/dbClient.js
> +  const query = async (queryString, ...args) => {
So to my understanding, it accepts up to three args: https://node-postgres.com/api/client

So the spread operator `...` is still useful just in case a callback function is provided. Which hasn't been seen yet in our project.

2021-03-23 00:27 UTC, forkitupforkitup commented on backend/graphql_api/lambda/db/dbClient.js
> +    const queryString = 'SELECT * FROM meeting WHERE id = $1'
Yes, I could have provided `[id]` as a second argument to the query function. But I was following the pattern I saw during the meeting. It seems like either way does work.

2021-03-24 01:34 UTC, forkitupforkitup commented
I have removed it

2021-03-24 02:13 UTC, forkitupforkitup commented
After Terry's PR and Senthil's PR were merged, I merged master into my branch.

2021-03-24 16:16 UTC, sent-hil approved these changes

2021-03-24 18:22 UTC, anna-kartynnik approved these changes

2021-03-25 03:31 UTC, merged

2021-04-02 06:32 UTC, anna-kartynnik commented on backend/agenda_upload_service/lambda/db/dbClient.js
> +  const query = async (queryString, ...args) => {
@sent-hil @forkitupforkitup please check the PR #171 which is connected with this discussion.