postgres: add new fields to meeting
codeforsanjose/gov-agenda-notifier pull request #205
Opened 2021-04-30 05:23 UTC by sent-hil

Closes #203

2021-04-30 05:32 UTC, anna-kartynnik commented
Could you please also add these new fields into 
https://github.com/codeforsanjose/gov-agenda-notifier/blob/f08a4fe482ae32f4685937634f23d30a6c785ef8/backend/graphql_api/lambda/graphql/apolloServer.js#L75-L84
Should I create a new issue for adding these fields into the corresponding mutations?

2021-04-30 05:50 UTC, sent-hil commented
@anna-kartynnik no need! i updated the PR...do you want me to update https://github.com/codeforsanjose/gov-agenda-notifier/blob/new-fields/backend/graphql_api/lambda/graphql/apolloServer.js#L39 to include the new fields?

2021-04-30 17:40 UTC, anna-kartynnik commented
Yes please, if you can update  https://github.com/codeforsanjose/gov-agenda-notifier/blob/new-fields/backend/graphql_api/lambda/graphql/apolloServer.js#L39,  https://github.com/codeforsanjose/gov-agenda-notifier/blob/new-fields/backend/graphql_api/lambda/graphql/apolloServer.js#L4 and their handlers https://github.com/codeforsanjose/gov-agenda-notifier/blob/develop/backend/graphql_api/lambda/graphql/resolvers/mutation.js#L39, https://github.com/codeforsanjose/gov-agenda-notifier/blob/develop/backend/graphql_api/lambda/graphql/resolvers/mutation.js#L180, that would be great!

2021-05-02 21:12 UTC, JMStudiosJoe approved these changes

2021-05-03 22:09 UTC, sent-hil commented
changing to blocked, there were new requests to the story...will try to get to them this week

2021-05-16 00:08 UTC, sent-hil commented
@anna-kartynnik @JMStudiosJoe this is ready again

2021-05-19 12:09 UTC, JMStudiosJoe submitted a review, later dismissed
lgtm

2021-05-19 21:34 UTC, anna-kartynnik requested changes
Looks good but has minor issues, see my comments.

2021-05-19 21:34 UTC, anna-kartynnik commented on backend/agenda_upload_service/lambda/db/dbClient.js
> +        INSERT INTO meeting(meeting_type, meeting_start_timestamp, virtual_meeting_url, created_timestamp, updated_timestamp, status, virtualMeetingId, callInInformation, emailBeforeMeeting, emailDur
Shouldn't it be
```
INSERT INTO meeting(meeting_type, meeting_start_timestamp, virtual_meeting_url, created_timestamp, updated_timestamp, status, virtual_meeting_id, call_in_information, email_before_meeting, email_during_meeting, eComment, city_of_san_jose_meeting, youtube_link)
```
? Note the snake case for the column names.

2021-05-19 21:34 UTC, anna-kartynnik commented on backend/agenda_upload_service/lambda/db/dbClient.js
> +        VALUES ($1, to_timestamp($2), $3, to_timestamp($4), to_timestamp($5), $6)
Forgot to add new values
```
VALUES ($1, to_timestamp($2), $3, to_timestamp($4), to_timestamp($5), $6, $7, $8, $9, $10, $11, $12, $13)
```
?

2021-05-19 21:34 UTC, anna-kartynnik commented on backend/graphql_api/lambda/graphql/apolloServer.js
> +        createMeeting(meeting_start_timestamp: String!, meeting_type: String, status: String, virtual_meeting_url: String, virtual_meeting_id: String!, call_in_information: String, email_before_meeti
It seems that a new meeting's date and time only should be required for creation (according to [these mocks](https://xd.adobe.com/view/ca32af76-bb04-4e66-b0f4-0ddbb6525ea5-9f61/screen/f446e0cf-d613-448d-9dac-1a0ec51f0b69/)). So I think `virtual_meeting_id` shouldn't be required.

2021-05-23 22:00 UTC, anna-kartynnik commented
@sent-hil if you don't mind I'd like to make the necessary changes to finish this PR.

2021-05-24 17:34 UTC, sent-hil commented
@anna-kartynnik that would be great, thank you

2021-05-26 05:59 UTC, anna-kartynnik approved these changes

2021-05-26 06:00 UTC, anna-kartynnik commented
@JMStudiosJoe I've fixed the comments above, so it's ready to be merged.

2021-05-26 21:37 UTC, merged

2021-05-27 02:27 UTC, sent-hil commented
Thank you @anna-kartynnik