Completed forgot password feature
codeforsanjose/gov-agenda-notifier pull request #253
Opened 2021-11-15 20:58 UTC by harshadajog

### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
New Feature

- Describe what changes are being made
1. Added ForgotPassword & SetNewPassword components.
2. Added GraphQL query & mutations Get_Token, update_token and reset_password.
3. Email sent on forgot password request.

- Describe why these changes are being made
https://trello.com/c/XC1mShgs/101-eng-forgot-password

- List the use cases and edge cases relevant to this PR
1. User clicks forgot password link.
2. User taken to reset password screen.
3. Cases - User exists in system. Negative - User not registered in system
4. Valid user requests send password reset email.
5. User clicks email link in inbox
6. Email link cases:
    valid,
    null,
    invalid,
    expired
7. If valid, user taken to set new password screen.
8. if Invalid, error shown (set new password screen is not shown)
9. if password reset success, success message shown
10. If error, error is displayed instead.

- Describe how errors will be handled. How will we know if this code breaks in production
Backend - try...catch. Logger.error/debug messages added
Frontend: handle all conditions

- Describe any external libraries/dependencies added or removed in this PR
None

- Describe any security risks are there regarding this change
The password token URL expires after 20 minutes.
But if anyone gets access to it, he can change password

- Describe how you tested these changes
Manual, Functional

- Link to relevant external documentation
None

--------------------------
### :clipboard: Mandatory Checklist

- [x] Example of a checked item (please remove when creating your Pull Request) 

- [x] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [x] Have you discussed these changes with the project leader(s)?
- [x] Do all variable and function names communicate what they do?
- [x] Were all the changes commented and / or documented?
- [x] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [x] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [x] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
### :framed_picture: Screenshots and Screen Recordings

#### Before

#### After

![image](https://user-images.githubusercontent.com/3578183/141852858-af62e094-a129-42d1-b33d-5ee921f28d39.png)

![image](https://user-images.githubusercontent.com/3578183/141852924-3489547a-1416-44b5-bb50-b1b209744e52.png)

https://user-images.githubusercontent.com/3578183/141852832-d6478c6b-e36b-474b-baa4-b5ab8a811af8.mp4

--------------------------
### :blue_book: Glossary
- PR = Pull Request

2021-11-16 22:22 UTC, jdunbrack requested changes
A few quick formatting/indentation changes, but everything else looks good.

2021-11-16 22:22 UTC, jdunbrack commented on frontend/src/components/ForgotPassword/ForgotPasswordRequest.jsx
> +  import './ForgotPasswordRequest.scss';
Stray indent

2021-11-16 22:22 UTC, jdunbrack commented on frontend/src/components/ForgotPassword/SetNewPassword.jsx
> +function SetNewPassword (){
Indentation is inconsistent inside function definition

2021-11-16 22:22 UTC, jdunbrack commented on frontend/src/components/ForgotPassword/SetNewPassword.jsx
> +  import './ForgotPasswordRequest.scss';
Stray Indents

2021-11-17 00:15 UTC, harshadajog commented on frontend/src/components/ForgotPassword/SetNewPassword.jsx
> +function SetNewPassword (){
Fixed

2021-11-17 00:16 UTC, harshadajog commented on frontend/src/components/ForgotPassword/SetNewPassword.jsx
> +  import './ForgotPasswordRequest.scss';
Fixed in latest commit

2021-11-17 00:16 UTC, harshadajog commented on frontend/src/components/ForgotPassword/ForgotPasswordRequest.jsx
> +  import './ForgotPasswordRequest.scss';
Fixed

2021-11-17 00:22 UTC, harshadajog commented
Fixed the indents. Will look into why ESLint didn't report the issues.

2021-11-17 22:42 UTC, jdunbrack approved these changes

2021-11-22 15:09 UTC, JMStudiosJoe approved these changes

2021-11-22 15:09 UTC, merged