Fixes all of the problems caused by ESLint in the frontend folder
codeforsanjose/gov-agenda-notifier pull request #83
Opened 2020-12-04 05:05 UTC by sepsol

2020-12-04 20:29 UTC, forkitupforkitup submitted a review, later dismissed
No problems running on my system

2020-12-07 23:43 UTC, jeffersonken19 commented on frontend/package.json
> +    "react-scripts": "^4.0.1",
Let's remove the carets from our dependencies:
See the section on "Why pin dependencies":
https://docs.renovatebot.com/dependency-pinning/

2020-12-07 23:47 UTC, jeffersonken19 commented on frontend/package.json
>      "twilio": "^3.50.0",
There are packages in this package.json that are backend only. Let's remove them. @sepsol @teohrt

2020-12-07 23:47 UTC, jeffersonken19 commented on frontend/package.json
> +    "react-scripts": "^4.0.1",
What was the reason for upgrading this package to a new major version?

2020-12-07 23:48 UTC, jeffersonken19 commented on frontend/src/components/AdminView/AdminNavigation/AdminNavigation.jsx
> +        // onClick={() => console.log('publish clicked')} // DEBUG: replace with publish action
Do we have a github issue to tag as a TODO here?

2020-12-07 23:49 UTC, jeffersonken19 commented on frontend/src/components/AdminView/AdminUploadView/AdminUploadView.jsx
> +    // TODO: Implement upload:
Github issue for this TODO?

2020-12-07 23:50 UTC, jeffersonken19 commented on frontend/src/components/AdminView/AdminView.jsx
> +      setTimeout(() => setMeetingIdList(TEST_MEETING_IDS), 1000); // MOCK API CALL
Github issue for this TODO?

2020-12-07 23:56 UTC, jeffersonken19 commented on frontend/src/index.jsx
> +  // const { loading, error, data } = useQuery(GET_ALL_MEETINGS_WITH_ITEMS);
Github issue link + TODO comment?

2020-12-08 00:28 UTC, terchiem commented on frontend/src/components/AdminView/AdminNavigation/AdminNavigation.jsx
> +        // onClick={() => console.log('publish clicked')} // DEBUG: replace with publish action
Created an issue for this: #84

2020-12-08 00:29 UTC, terchiem commented on frontend/src/components/AdminView/AdminView.jsx
> +      setTimeout(() => setMeetingIdList(TEST_MEETING_IDS), 1000); // MOCK API CALL
Created an issue for this: #85

2020-12-08 01:03 UTC, terchiem requested changes
Left one minor comment about some code that was refactored. I agree with Annie that we should keep the package versions as they were before.

2020-12-08 03:07 UTC, sepsol commented on frontend/package.json
> +    "react-scripts": "^4.0.1",
it was probably done while I ran `npm audit fix`. I remember I was forced to do that in order for ESLint to work.

2020-12-08 03:10 UTC, sepsol commented on frontend/src/index.jsx
> +  // const { loading, error, data } = useQuery(GET_ALL_MEETINGS_WITH_ITEMS);
I commented those out because of the error we were getting with the `console.log()` statement - as you suggested. And when I did that I had to comment out everything that was linked to that `console.log()` on line `41`. Otherwise, it would throw us an error.

2020-12-08 03:15 UTC, sepsol commented on frontend/package.json
>      "twilio": "^3.50.0",
Those weren't added in this branch.

2020-12-08 07:28 UTC, anna-kartynnik commented on frontend/package.json
> +    "eslint": "^7.14.0",
Guys, ESLint is already added to the project. All these dependencies except `eslint-config-airbnb` are already included in the project via dependency `react-scripts` (although with different versions). See the corresponding lines in `package-lock.json`:

https://github.com/codeforsanjose/gov-agenda-notifier/blob/4fad93b6b43bbd4b2c893e2af7d8417818fe3393/frontend/package-lock.json#L12354-L12361

I don't see why we should reintroduce `eslint` here if it's already present.

2020-12-08 07:28 UTC, anna-kartynnik commented on frontend/src/index.jsx
> +  // const { loading, error, data } = useQuery(GET_ALL_MEETINGS_WITH_ITEMS);
Just a note: you can add `// eslint-disable-next-line` to mute ESLint for one line of code. For example, you can add it before `console.log`  statement. If you know it's temporary, it can be appropriate.

2020-12-08 07:28 UTC, anna-kartynnik commented on frontend/.eslintrc.json
> +{
To avoid confusions, it's better to have ESLint configuration in one place. Right now we have it in this file and in `package.json`:

https://github.com/codeforsanjose/gov-agenda-notifier/blob/4fad93b6b43bbd4b2c893e2af7d8417818fe3393/frontend/package.json#L47-L49

2020-12-09 06:40 UTC, sepsol commented on frontend/package.json
> +    "eslint": "^7.14.0",
They were all automatically added with the `./node_mdules/.bin/eslint init` command which was provided in [the tutorial](https://create-react-app.dev/docs/setting-up-your-editor/) shared by Annie and Trace.

2020-12-09 06:41 UTC, sepsol commented on frontend/.eslintrc.json
> +{
The config in the `package.json` is the default one that we had previously. The other one was the one generated by the `init` command I mentioned earlier.

2020-12-09 06:42 UTC, sepsol commented on frontend/src/index.jsx
> +  // const { loading, error, data } = useQuery(GET_ALL_MEETINGS_WITH_ITEMS);
Ok, will do it for all `console.log`s.

2020-12-09 18:45 UTC, anna-kartynnik commented on frontend/.eslintrc.json
> +{
I think it's better to have only one config, hence I would remove this entry from `package.json` 🤔.

2020-12-10 00:01 UTC, sepsol commented on frontend/.eslintrc.json
> +{
Done! Thanks for your feedback :)

2020-12-10 00:30 UTC, terchiem approved these changes

2020-12-10 00:30 UTC, sepsol commented on frontend/src/components/AdminView/AdminView.jsx
> +      setTimeout(() => setMeetingIdList(TEST_MEETING_IDS), 1000); // MOCK API CALL
Added the link as a comment inside the code.

2020-12-10 00:30 UTC, sepsol commented on frontend/src/components/AdminView/AdminNavigation/AdminNavigation.jsx
> +        // onClick={() => console.log('publish clicked')} // DEBUG: replace with publish action
Added the link as a comment inside the code.

2020-12-14 02:39 UTC, teohrt commented on frontend/package.json
>      "twilio": "^3.50.0",
Weird. I can make a PR for that after this one get's into master.

2020-12-14 02:42 UTC, teohrt approved these changes
Looks great! I'll make a follow up PR for the package.json changes that include the unnecessary backend dependencies.

2020-12-15 02:13 UTC, forkitupforkitup approved these changes

2020-12-15 02:15 UTC, merged